---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
  adminAPI:
    enabled: false
  metricsEnabled: false
  logRequestPayloads: false

engine:
  defaultPolicyVersion: "default"

auxData:
  jwt:
    disableVerification: true

storage:
  driver: disk
  disk:
    directory: "/policies"
    watchForChanges: true

telemetry:
  disabled: true
